### PR TITLE
Extent error check in GetMechanismList to allow a CKR_BUFFER_TOO_SMAL…

### LINKED ISSUE #30: GetMechanismList fails with CKR_BUFFER_TOO_SMALL on first call
When calling GetMechanismList on a Gemalto .NET Token the C function will return CKR_BUFFER_TOO_SMALL on the first call (with the Mechanism List being a NULL Pointer).
This is apparently in violation of the specs which states that the function should return CKR_OK. 

However i don't see much harm done to extend the error check in pkcs11.go:118 to be:
if (e != CKR_OK && e != CKR_BUFFER_TOO_SMALL) {
    return e;
}

With this addition i was able to successfully query the supported mechanisms from the Gemalto card.

Maybe someone can cross-check how this is handled in other pkcs11 implementations? The Token works fine in other applications.

### PR DESCRIPTION
**Pull request by FStelzer**
…L result when passing a NULL pointer

This allow the lib to work with gemaltos pkcs11 library.
Fixes #30

### CODE REVIEW

File: pkcs11.go [hunk 1]
```diff
@@ -115,7 +115,7 @@ CK_RV GetMechanismList(struct ctx * c, CK_ULONG slotID,
 {
 	CK_RV e =
 	    c->sym->C_GetMechanismList((CK_SLOT_ID) slotID, NULL, mechlen);
-	if (e != CKR_OK) {
+	if (e != CKR_OK && e != CKR_BUFFER_TOO_SMALL) {
```
Comment (miekg) [inline pkcs11.go]: maybe add a comment about gemelto here  as well?
